import Avatar from '../src/images/7309682.png'
import bg1 from '../src/images/bg/bg-1.jpg'
import bg2 from '../src/images/bg/bg-2.jpg'
import bg3 from '../src/images/bg/bg-9.jpg'
import bg4 from '../src/images/bg/bg-8.jpg'

export const userData = [
    {
        _id: 1,
        FirstName: "Abcd",
        LastName: "Efg",
        Email: "Abcd@gmail.com",
        Country_Code: "101010",
        Phone: "1010101010",
        Password: "Abcd123",
        Confirm_Password: "Abcd123",
        referral_Name: "1234",
        Location: "Abcd",
        Profile_Pic: Avatar,
        Pan_Number: "Abcd",
        Adhar_Number: "Abcd",
        Bank_Holder_Name: "Abcd",
        Ac_Number: "Abcd",
        IFSC_Code: "Abcd",
        Bank_Name: "Abcd",
        UPI: "Abcd",
        isActive: false
    },
    {
        _id: 2,
        FirstName: "Abcd",
        LastName: "Efg",
        Email: "Abcd@gmail.com",
        Country_Code: "101010",
        Phone: "1010101010",
        Password: "Abcd123",
        Confirm_Password: "Abcd123",
        referral_Name: "1234",
        Location: "Abcd",
        Profile_Pic: bg1,
        Pan_Number: "Abcd",
        Adhar_Number: "Abcd",
        Bank_Holder_Name: "Abcd",
        Ac_Number: "Abcd",
        IFSC_Code: "Abcd",
        Bank_Name: "Abcd",
        UPI: "Abcd",
        isActive: false
    },
    {
        _id: 3,
        FirstName: "Abcd",
        LastName: "Efg",
        Email: "Abcd@gmail.com",
        Country_Code: "101010",
        Phone: "1010101010",
        Password: "Abcd123",
        Confirm_Password: "Abcd123",
        referral_Name: "1234",
        Location: "Abcd",
        Profile_Pic: bg2,
        Pan_Number: "Abcd",
        Adhar_Number: "Abcd",
        Bank_Holder_Name: "Abcd",
        Ac_Number: "Abcd",
        IFSC_Code: "Abcd",
        Bank_Name: "Abcd",
        UPI: "Abcd",
        isActive: false
    },
    {
        _id: 4,
        FirstName: "Abcd",
        LastName: "Efg",
        Email: "Abcd@gmail.com",
        Country_Code: "101010",
        Phone: "1010101010",
        Password: "Abcd123",
        Confirm_Password: "Abcd123",
        referral_Name: "1234",
        Location: "Abcd",
        Profile_Pic: bg3,
        Pan_Number: "Abcd",
        Adhar_Number: "Abcd",
        Bank_Holder_Name: "Abcd",
        Ac_Number: "Abcd",
        IFSC_Code: "Abcd",
        Bank_Name: "Abcd",
        UPI: "Abcd",
        isActive: false
    },
    {
        _id: 5,
        FirstName: "Abcd",
        LastName: "Efg",
        Email: "Abcd@gmail.com",
        Country_Code: "101010",
        Phone: "1010101010",
        Password: "Abcd123",
        Confirm_Password: "Abcd123",
        referral_Name: "1234",
        Location: "Abcd",
        Profile_Pic: bg4,
        Pan_Number: "Abcd",
        Adhar_Number: "Abcd",
        Bank_Holder_Name: "Abcd",
        Ac_Number: "Abcd",
        IFSC_Code: "Abcd",
        Bank_Name: "Abcd",
        UPI: "Abcd",
        isActive: false
    }
]